environment:
  nodejs_version: 11.0.0

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - cinst -y nsis
  - SET PATH=C:\Program Files\NSIS\;C:\Program Files (x86)\NSIS\;%PATH%
  - npm ci --only=production

build_script:
  - cmd: node lib\scripts\packageDesktopApp.js

test_script:
  - node --version
  - npm --version

artifacts:
  - path: code-nwjs-build\versions\**\*
    name: build

version: "{build}"

skip_tags: true

deploy:
  - provider: S3
    access_key_id:
      secure: 1joZTNZgmvLkKm8loxEpluxvQfInd6tssEaIysW4ONs=
    secret_access_key:
      secure: V7c3H3iFazbpHOxThQMIkcZCp99uEBOAcE8v75qMZAvap9SwbGprXuQ4KIiTSDvF
    bucket: strawbees-downloads-stage
    region: us-east-1
    set_public: true
    folder:
    artifact: build
    on:
      branch: develop
  - provider: S3
    access_key_id:
      secure: 1joZTNZgmvLkKm8loxEpluxvQfInd6tssEaIysW4ONs=
    secret_access_key:
      secure: V7c3H3iFazbpHOxThQMIkcZCp99uEBOAcE8v75qMZAvap9SwbGprXuQ4KIiTSDvF
    bucket: strawbees-downloads-production
    region: us-east-1
    set_public: true
    folder:
    artifact: build
    on:
      branch: master
